In [30]:
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.impute import SimpleImputer

Taking care of Missing Data

In [31]:
dataset = pd.read_csv('./student_performance.csv')
x = dataset.iloc[:, :-2].values
y = dataset.iloc[:, -2].values

# print(x,"x-data")
print(y,"y-data")

imputer = SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(x[:, 1:4])
x[:, 1:4] = imputer.transform(x[:, 1:4])

print(x,"x-sklearn-data")

['High' 'Medium' 'Low' 'High' 'Medium' 'High' 'Low' 'Medium' 'Low' 'High'] y-data
[['Male' 85.0 15.0 78.0 1]
 ['Female' 90.0 20.0 85.0 2]
 ['Male' 78.0 10.0 65.0 0]
 ['Female' 92.0 25.0 90.0 3]
 ['Male' 88.0 18.0 82.0 2]
 ['Female' 95.0 30.0 88.0 1]
 ['Male' 70.0 8.0 60.0 0]
 ['Female' 85.0 17.0 78.22222222222223 1]
 ['Male' 82.0 12.0 70.0 2]
 ['Female' 91.0 22.0 86.0 3]] x-sklearn-data


Encoding Categorical Data

Encoding the Independent Variable

In [32]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[0])],remainder='passthrough')
X = np.array(ct.fit_transform(x))


In [33]:
print(X)

[[0.0 1.0 85.0 15.0 78.0 1]
 [1.0 0.0 90.0 20.0 85.0 2]
 [0.0 1.0 78.0 10.0 65.0 0]
 [1.0 0.0 92.0 25.0 90.0 3]
 [0.0 1.0 88.0 18.0 82.0 2]
 [1.0 0.0 95.0 30.0 88.0 1]
 [0.0 1.0 70.0 8.0 60.0 0]
 [1.0 0.0 85.0 17.0 78.22222222222223 1]
 [0.0 1.0 82.0 12.0 70.0 2]
 [1.0 0.0 91.0 22.0 86.0 3]]


Encoding the Dependent Variable

In [34]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit_transform(y)

array([0, 2, 1, 0, 2, 0, 1, 2, 1, 0])