# Tensors
- Tensors are the fundamental data structure in TensorFlow, representing multi-dimensional arrays.
- They can be thought of as generalizations of vectors and matrices to higher dimensions.
- Tensors can have different ranks, which indicate the number of dimensions they have:
  - Rank 0: Scalar (a single value)
  - Rank 1: Vector (a one-dimensional array)
  - Rank 2: Matrix (a two-dimensional array)
  - Rank n: n-dimensional array

# TensorFlow
- TensorFlow is an open-source machine learning framework developed by Google.
- It provides a comprehensive ecosystem for building and deploying machine learning models.
- TensorFlow supports various machine learning tasks, including deep learning, reinforcement learning, and more.
- It allows developers to create complex neural networks and perform computations efficiently using data flow graphs.

## Example Code
```python
import tensorflow as tf
# Create a constant tensor
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
# Print the tensor
print(tensor)   

In [ ]:
!python --version
!pip install --upgrade pip
!pip install tensorflow

In [5]:
# constant with tensorflow

import tensorflow as tf
string_tensor = tf.constant("Hello, TensorFlow!")
print(string_tensor)

tf.Tensor(b'Hello, TensorFlow!', shape=(), dtype=string)


In [14]:
# Rank and Degree of Tensors ?

scalar_tensor = tf.constant(5)

print("Scalar Rank 0",scalar_tensor)

vector_tensor = tf.constant([1,2,3])

print("vector Rank 1",vector_tensor)

matrix_tensor = tf.constant([[1,2],[3,4]])

print("matrix Rank 2",matrix_tensor)

# Rank tensor

rank = tf.rank(matrix_tensor)
print("Rank :",rank)

shape = matrix_tensor.shape

print("shape :",shape)

Scalar Rank 0 tf.Tensor(5, shape=(), dtype=int32)
vector Rank 1 tf.Tensor([1 2 3], shape=(3,), dtype=int32)
matrix Rank 2 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
Rank : tf.Tensor(2, shape=(), dtype=int32)
shape : (2, 2)


# Ones in TensorFlow
- The `tf.ones` function creates a tensor filled with ones.
```python
ones_tensor = tf.ones((2, 3))  # Creates a 2x3 tensor filled with ones
print(ones_tensor)
# Zeros in TensorFlow
- The `tf.zeros` function creates a tensor filled with zeros.
```python   
zeros_tensor = tf.zeros((2, 3))  # Creates a 2x3 tensor filled with zeros
print(zeros_tensor)
# Random Tensors in TensorFlow
- The `tf.random` module provides functions to create tensors with random values.
```python
random_tensor = tf.random.uniform((2, 3), minval=0, maxval=10)  # Creates a 2x3 tensor with random values between 0 and 10
print(random_tensor)
# Operations on Tensors
- TensorFlow supports various operations on tensors, such as addition, multiplication, and reshaping.
```python
# Element-wise addition
tensor_a = tf.constant([[1, 2, 3], [4, 5, 6]])
tensor_b = tf.constant([[7, 8, 9], [10, 11, 12]])
result_add = tf.add(tensor_a, tensor_b)  # Adds the two tensors element
print(result_add)
# Element-wise multiplication
result_mul = tf.multiply(tensor_a, tensor_b)  # Multiplies the two
print(result_mul)
# Reshaping a tensor
reshaped_tensor = tf.reshape(tensor_a, (3, 2))  # Reshapes the tensor to a different shape
print(reshaped_tensor)
# TensorFlow Version
- To check the version of TensorFlow installed, you can use the following code:
```python
print(tf.__version__)  # Prints the version of TensorFlow
```


In [18]:
tensorone = tf.ones([1,2,3])
print(tensorone,"tensorone")
tensor2 = tf.reshape(tensorone,[2,3,1])

print(tensor2)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32) tensorone
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)


# Placeholders example
- Placeholders are used to define tensors that will be provided later during the execution of a TensorFlow graph.
```python
import tensorflow as tf
# Create a placeholder for a tensor of shape [None, 2]
placeholder_tensor = tf.placeholder(tf.float32, shape=[None, 2])
# Print the placeholder tensor
print(placeholder_tensor)



In [22]:
# placeholder exapmle
# Define an input tensor (like placeholder) for use in Keras model
input_tensor = tf.keras.Input(shape=(2,), dtype=tf.float32)
print(input_tensor)

<KerasTensor shape=(None, 2), dtype=float32, sparse=False, ragged=False, name=keras_tensor>
